<?php
/* ************************************************************************

   Barclaycard ePDQ CPI Prestashop Payment Module v2.4

   http://www.prestashop-epdq.org/
   http://sourceforge.net/projects/prestashop-epdq/

   Copyright:
     Copyright 2009-2011 (c) Richard Hall, United Kingdom, http://www.richardhall.me.uk/

   License:
     OSL3.0: Licensed under the Open Software License version 3.0, http://www.opensource.org/licenses/osl-3.0.php
	 See the license.txt file in the project's compressed distributable for details.

   Authors:
     * Richard Hall (richardhall)
     
************************************************************************ */

/**
 * Produces a human-readable explanation of an Electronic Commerce Indicator (ECI)
 * status response code as generated by MasterCard SecureCode or Verified by Visa
 * as part of the Internet Authentication initiative.
 */
 function epdqAuthResponse($ecistatus)
{
  switch( $ecistatus )
  {
 
	case '0':  //The merchant took the customer's credit card and swiped it through a machine that read the magnetic strip data of the card.
		$ecidetail = 'Swiped';
      break;
  	case '1':  //The merchant received the customer's financial details over the phone or via fax/mail, but does not have the customer's card at hand.
		$ecidetail = 'Manually keyed (MOTO) (card not present)';
      break;
  	case '2':  //The customer's first transaction was a Mail Order / Telephone Order transaction, i.e. the customer gave his financial details over the phone or via mail/fax to the merchant. The merchant either stored the details himself or had these details stored in our system using an Alias and is performing another transaction for the same customer (recurring transaction).
		$ecidetail = 'Recurring (from MOTO)';
      break;
  	case '3':  //Partial payment of goods/services that have already been delivered, but will be paid for in several spread payments. 
		$ecidetail = 'Installment payments';
      break;
  	case '4':  //The customer is physically present in front of the merchant. The merchant has the customer's card at hand. The card details are manually entered, the card is not swiped through a machine.
		$ecidetail = 'Manually keyed, card present';
      break;
  	case '5':  //The cardholder's 3-D Secure identification was successful, i.e. there was a full authentication. (Full thumbs up) 
		$ecidetail = 'Cardholder identification successful';
      break;
  	case '6':  //Merchant supports identification but not cardholder, The merchant has a 3-D Secure contract, but the cardholder's card is not 3-D Secure or is 3-D Secure but the cardholder is not yet in possession of the PIN (Half thumbs up). Conditional payment guarantee rules apply.
		$ecidetail = 'Merchant supports identification but not cardholder, The merchant has a 3-D Secure contract, but the cardholder\'s card is not 3-D Secure or is 3-D Secure but the cardholder is not yet in possession of the PIN (Half thumbs up). Conditional payment guarantee rules apply.';
      break;
  	case '7':  //The merchant received the customer's financial details via a secure (SSL encrypted) website (either the merchant's website or our secure platform).
		$ecidetail = 'E-commerce with SSL encryption';
      break;
  	case '8':  //
		$ecidetail = '';
      break;
  	case '9':  //The customer's first transaction was an e-Commerce transaction, i.e. the customer entered his financial details himself on a secure website (either the merchant's website or our secure platform). The merchant either stored the details himself or had these details stored in our system using an Alias and is now performing another transaction for the same customer (recurring transaction), using the Alias details. 
		$ecidetail = 'Recurring (from e-commerce)';
      break;

  }
  return $ecidetail;
}
