<?php
/* ************************************************************************

   Barclaycard ePDQ CPI Prestashop Payment Module v2.4

   http://www.prestashop-epdq.org/
   http://sourceforge.net/projects/prestashop-epdq/

   Copyright:
     Copyright 2009-2011 (c) Richard Hall, United Kingdom, http://www.richardhall.me.uk/

   License:
     OSL3.0: Licensed under the Open Software License version 3.0, http://www.opensource.org/licenses/osl-3.0.php
	 See the license.txt file in the project's compressed distributable for details.

   Authors:
     * Richard Hall (richardhall)
     
************************************************************************ */

/**
 * Produces a human-readable explanation of an ECI Status response code as
 * generated by MasterCard SecureCode or Verified by Visa Internet authentication.
 */
function epdqTransactionStatusResponse( $transactionstatus )
{
  switch( $transactionstatus )
  {
    case 'Success':
      $response = 'Success';
      break;
    case 'DECLINED':
      $response = 'Declined';
      break;
    case 'DECLINED. This store does not accept American Express. Please try again using a different card type.':
      $response = 'Declined - American Express cards not accepted';
      break;
    case 'DECLINED. This store does not accept this card type. Please try again using a different card type.':
      $response = 'Declined - card type not accepted';
      break;
    case 'Awaiting confirmation. Please contact the merchant and quote Ref 2.':
      $response = 'Awaiting confirmation - issuing bank refers transaction';
      break;
    case 'Awaiting confirmation. Please contact the merchant and quote Ref 3.':
      $response = 'Awaiting confirmation - issuer has requested voice authorisation';
      break;
    case 'An error has occurred. Please contact the merchant and quote Ref 51.':
      $response = 'An error has occurred - connection timed out';
      break;
    case 'There was a Problem processing your order. Please contact the merchant and quote Ref 3.':
      $response = 'Problem processing order - issuer has requested voice authorisation';
      break;
    case 'There was a Problem processing your order. Please contact the merchant and quote Ref 50.':
      $response = 'Problem processing order - issuer has declined the card';
      break;
    case 'There was a Problem processing your order. Please contact the merchant and quote Ref 51.':
      $response = 'Problem processing order - timed out connecting to payment engine';
      break;
    case 'There was a Problem processing your order. Please contact the merchant and quote Ref 52.':
      $response = 'Problem processing order - problem connecting to payment engine';
      break;
    case 'There was a Problem processing your order. Please contact the merchant and quote Ref 500.':
      $response = 'Problem processing order - declined as fraudulent';
      break;
    case 'There was a Problem processing your order. Please contact the merchant and quote Ref 501.':
      $response = 'Problem processing order - authorised but declined due to configured fraud rules';
      break;
    case 'There was a Problem processing your order. Please contact the merchant and quote Ref 502.':
      $response = 'Problem processing order - authorised but requires reviewing manually';
      break;
    case 'There was a Problem processing your order. Please contact the merchant and quote Ref 1053.':
      $response = 'Problem processing order - issuer requests card be retained';
      break;
    case 'There was a Problem processing your order. Please contact the merchant and quote Ref 1054.':
      $response = 'Problem processing order - response from issuer not recognised';
      break;
  }
  return $response;
}
